name: Dependable

on:
  workflow_run:
    workflows: [Initial]
    types:
      - completed

jobs:
  print:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request'
      && github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Print Dependable
        run: echo 'Dependable'
